import { SxProps, Theme } from "@mui/material";

export const heroStyles: Record<string, SxProps<Theme>> = {
  container: {
    height: "100vh",
    width: "100vw",
    // backgroundImage:
    //   "url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_0w0iq_uYDzYZwDS2xDf0VVa_tttl07RKfA&s')",
    // backgroundSize: "cover",
    // backgroundPosition: "center",
    // backgroundAttachment: "fixed",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    position: "relative",
    color: "#fff",
    m: 0,
    p: 0,
    fontFamily: "'Roboto', sans-serif",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    // backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 1,
  },
  heading: {
    fontWeight: "bold",
    fontSize: { xs: "2.5rem", md: "3rem" },
    mb: 2,
    zIndex: 2,
    textShadow: "2px 2px 4px rgba(0, 0, 0, 0.7)",
    lineHeight: 1.2,
    px: 2,
  },
  subHeading: {
    fontWeight: 300,
    fontSize: { xs: "1rem", md: "1.2rem" },
    mb: 3,
    zIndex: 2,
    // textShadow: "2px 2px 4px rgba(0, 0, 0, 0.7)",
    lineHeight: 1.5,
    px: 2,
  },
  button: {
    mt: 3,
    px: 4,
    py: 1.5,
    fontSize: "1rem",
    textTransform: "uppercase",
    zIndex: 2,
    backgroundColor: "#ff6600",
    color: "#fff",
    border: "none",
    "&:hover": {
      backgroundColor: "#e65c00",
    },
  },
};
